### ISSUE TITLE
Bloomreach CMS integration with Docker and docker-compose and optimisation

### ISSUE THREAD

**Issue by niklaswinkels** [bloomreach/contribution-program#1]

**Comment by niklaswinkels** [comment]
@Laazarus let's keep track of the progress in this issue - I'll ask our editorial team to take a look at your draft and have an image created to go with the article 🎉😊

**Comment by Laazarus** [comment]
Hey Niklas,

I created a git lab repo with the scripts in our gitlab repo.

For now is private only for the logged in users. If you do not have a git lab account i will make it public.
The address is 
https://gitlab.com/AlphaCogs/bloomreach-cms-integration-with-docker.git

**Comment by niklaswinkels** [comment]
@Laazarus Could you publish the scripts to a public repo as well? Otherwise, it'll be hard for other people who don't have an account to follow along with your article :)

**Comment by Laazarus** [comment]
@niklaswinkels  Done it is public now :)

**Comment by niklaswinkels** [comment]
great @Laazarus. Once one of our copywriters drops by to leave feedback, we're ready to publish. I scheduled the publication for January 7th to give the guys some time to create an image as well - does that work for you?

**Comment by Laazarus** [comment]
Hello niklas,
Sure I am about to give you a more recent version that includes the way to secure the site with Https for free always with docker.
Is that of interest?

On 7 Dec 2018 9:12 am, Niklas Winkels <notifications@github.com> wrote:

great @Laazarus<https://github.com/Laazarus>. Once one of our copywriters drops by to leave feedback, we're ready to publish. I scheduled the publication for January 7th to give the guys some time to create an image as well - does that work for you?

**Comment by niklaswinkels** [comment]
Hi @Laazarus - your blog post is now online at https://developers.bloomreach.com/blog/2019/bloomreach-cms-integration-with-docker-and-docker-compose.html 🎉

Thanks again for contributing 😊
