### ISSUE TITLE
Blog About How Configuration Management is Done at Bloomreach

### ISSUE THREAD

**Issue by VarunWachaspati** [bloomreach/contribution-program#6]
Would like to pen down an article regarding the robust configuration management system that we have built at Bloomreach. Discuss about how it achieves consistency and availability along with an overview of the entire architecture.

**Comment by niklaswinkels** [comment]
Thanks for adding it here @VarunWachaspati :) Now published at: https://developers.bloomreach.com/blog/2019/how-bloomreach-built-a-scalable-configuration-management-system.html 🎉
